---
version: 0.2

phases:
  build:
    commands:
      # Todo: revert this after testing
      # - aws-nuke --config aws-nuke.yaml --quiet --force --no-dry-run
      - aws-nuke --config aws-nuke.yaml --quiet --force
